

const API_APP_VERSION = process.env.API_APP_VERSION;
const API_APPDALACOM_VERSION = process.env.API_APPDALACOM_VERSION;
const API_DALAVN_VERSION = process.env.API_DALAVN_VERSION;
const API_LIB_VERSION = process.env.API_LIB_VERSION;
const API_SHARES_VERSION = process.env.API_SHARES_VERSION;


module.exports = {
	API_APP_VERSION,
	API_APPDALACOM_VERSION,
	API_DALAVN_VERSION,
	API_LIB_VERSION,
	API_SHARES_VERSION	
};



