DROP EVENT IF EXISTS delete_ip_block_event;
CREATE  EVENT delete_ip_block_event 
ON SCHEDULE EVERY 15 MINUTE STARTS '2023-03-29 19:10:24' 
ON COMPLETION NOT PRESERVE DISABLE ON SLAVE 
COMMENT 'delete ip block data' 
DO TRUNCATE TABLE dala_ip_block;