

const API_APP_VERSION = "v5";
const API_APPDALACOM_VERSION = "v5";
const API_DALAVN_VERSION = "v5";
const API_LIB_VERSION = "v5";
const API_SHARES_VERSION = "v5";


module.exports = {
	API_APP_VERSION,
	API_APPDALACOM_VERSION,
	API_DALAVN_VERSION,
	API_LIB_VERSION,
	API_SHARES_VERSION	
};



